export interface Reference {
    /**
     * property of schema that references the target model
     */
    property: string;
    /**
     * name of the target model
     */
    modelName: string;
    /**
     * indicates that the property is an array
     */
    isArray?: boolean;
}

export default interface ModelSettings {
    /**
     * if true, adds an autogenerated `createdAt` and `updatedAt` property to the schema
     */
    timestamps?: boolean;
    /**
     * if true, adds an `isDeleted` flag to the schema, which is set to true instead of deleting the data
     */
    softDelete?: boolean;
    /**
     * list of references for the model
     */
    references?: Reference[];
}
